/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "CyScBoostClk.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "YM_A1_aliases.h"
#include "YM_A1.h"
#include "YM_A0_aliases.h"
#include "YM_A0.h"
#include "YM_RD_aliases.h"
#include "YM_RD.h"
#include "YM_WR_aliases.h"
#include "YM_WR.h"
#include "YM_CS_aliases.h"
#include "YM_CS.h"
#include "YM_Data_aliases.h"
#include "YM_Data.h"
#include "SN_WE_aliases.h"
#include "SN_WE.h"
#include "YM_IC_aliases.h"
#include "YM_IC.h"
#include "YM_CLK_aliases.h"
#include "YM_CLK.h"
#include "SN_CLK_aliases.h"
#include "SN_CLK.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

